### ISSUE TITLE
Couldn't read a new frame

### ISSUE THREAD

**Issue by fc73** [kmpm/py-asyncio-goproapi#1]
Hi,
I met some problems when I was trying to get the frames from the live stream. Here is the error:
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:856)
warning: udp://10.5.5.9:8554 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:857)

It seems like there is no frame generated by the life stream since the images generated are always 0kb.
The running environment is python3.6 windows 7.

Any help is appreciated!

BR
Cheng

**Comment by kmpm** [comment]
Sorry... I'v abandoned development on this project. Will delete it eventually.
There are loads of stuff that is not yet converted to asyncio.

All new work is done in a new project https://github.com/kmpm/py-aiogopro . That one is far from complete but I'll implement more and more. It will be similar in api to this but I wanted to do stuff differently.
